### ISSUE TITLE
Can not pip install polygon3 as I use anaconda python 3.7.6

### ISSUE THREAD

**Issue by derekcbr** [Mrlution/RectilinearPackingProblemSolver#2]
Hi, is there a solution to fix the problem? Is the maximum supported version is python 3.6? Which python version is suitable for this application?

**Comment by Mrlution** [comment]
try `pip install Polygon3`, Do you write 'Polygon3 ' with a capital 'P'?

**Comment by derekcbr** [comment]
> try `pip install Polygon3`, Do you write 'Polygon3 ' with a capital 'P'?

Thanks! Done!
