### ISSUE TITLE
How to nest a large number of parts?

### ISSUE THREAD

**Issue by derekcbr** [Mrlution/RectilinearPackingProblemSolver#3]
suppose I have a large number of parts which need to be nested into equally same sized master panels? How to process the part data sets so that  it can be integrated with your algorithm?

**Comment by Mrlution** [comment]
Here are two things that could work for you.
1. transfor your own data to the format in data/polygon_area_etc_input_id.txt
2. If you don't like method 1, you can read the function " load_input_file" in tools/input_utls.py, and process your data in your own way

**Comment by Mrlution** [comment]
sorry for the spaghetti code   =￣ω￣=

**Comment by derekcbr** [comment]
> Here are two things that could work for you.
> 
> 1. transfor your own data to the format in data/polygon_area_etc_input_id.txt
> 2. If you don't like method 1, you can read the function " load_input_file" in tools/input_utls.py, and process your data in your own way

Suppose the total parts need more than one master panels to contain, say in total 5 container panels. At first I use container no. 1 to nest the parts, and then no. 2,3,4,5. How do I sort the parts list in the beginning so that all the parts can be nested into 5 containers by the right order?

**Comment by Mrlution** [comment]
oh, I understand. sorry i am not an English speaker.
you can set settings.BIN_NORMAL  in main.py as your container panel size. and then in line 523 of nest.py you may get a list named solution, each item of solution is a bin. 
all bin have the same size, without order.
And I am preparing my test, I may be slow to reply.

**Comment by derekcbr** [comment]
> oh, I understand. sorry i am not an English speaker.
> you can set settings.BIN_NORMAL in main.py as your container panel size. and then in line 523 of nest.py you may get a list named solution, each item of solution is a bin.
> all bin have the same size, without order.
> And I am preparing my test, I may be slow to reply.

Indeed useful!
